spring:
  datasource:
    url: jdbc:mysql://localhost:3306/whatscooking
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    main:
      allow-circular-references: true

  server:
    servlet:
      context-path: /whatscooking


